@echo off
echo Starting Yu-Gi-Oh! Deck Builder...
echo.
echo Installing dependencies if needed...
pip install -r requirements.txt
echo.
echo Starting application...
python yugioh_deck_builder.py
pause
